name: SVL Linter

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Verible Linter
        uses: chipsalliance/verible-linter-action@v2.0
        with:
          verible_version: "v0.0-3622-g6c32d4b9"
          paths: |
            src
          extensions: |
            .sv
            .v
            .svh
            .vh